#!/usr/bin/env bash

# This file is exclusively for setting up devtools in a dev container/codespace.

# Bash
export DEVTOOLS_BASH=true
export DEVTOOLS_BASH_DEV_HOME=~/
export DEVTOOLS_BASH_REPO_HOME=~/
export DEVTOOLS_BASH_DEVTOOLS_HOME=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
export DEVTOOLS_BASH_TOOLS_HOME=~/tools
export DEVTOOLS_BASH_TOOLS_BIN_HOME=~/tools/bin
# Feature toggles
export DEVTOOLS_BASH_FEATURES_COMMANDS=true
export DEVTOOLS_BASH_FEATURES_GIT_EXTENDED=true
export DEVTOOLS_BASH_FEATURES_GIT_COMPLETION=true
export DEVTOOLS_BASH_FEATURES_GIT_PROMPT=true
# Use only one of the following: ---
export DEVTOOLS_BASH_FEATURES_USE_1PASSWORD_AGENT=false
export DEVTOOLS_BASH_FEATURES_USE_SSH_AGENT=false
# ---

# Git
export DEVTOOLS_GIT=true
# Feature toggles
export DEVTOOLS_GIT_FEATURES_CONFIG=true
export DEVTOOLS_GIT_FEATURES_CONFIG_NAME=andrew-codes
export DEVTOOLS_GIT_FEATURES_CONFIG_SIGNINGKEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHGX0BrMpr5mm/maYDNJJhBrn1lvjgy+9//ufn+QV5rC8MQpkakTKi3qzEQ22Xw4bOPb59C80TkH8T6ur4Ygb0oPMhFCQoBpd1rabQCIISSwi+I4bth58h8Jl/tXdiNclfTyPHNBPxRTjOGG9Op+Zu8EQtd4QUinf3iFFKJ4Wyk9cuHbKGYkhKnQG/u1LD+IJ6y2pt4Cdh2hnO2HIsSKOp6djx8zuCOMyguN1giFsa4gmd3/TcNO/O/p6G1Xs3v1H9KWWtXVL0gRRd1NTbnbqyuBmlBu2wKWVbznlf7Jjkb0asophnHBSsIcwJU079YGWfCVeZ0eoq/goDcI2Nj+FkNTJsJxuOwCUCBCikPZwUstU1cRAhTP72pu08ZQXM/B+uF2lDCLVu+Kui2bZQbOjNGunRnsFfer7XGpfqIeaYd8zJNFQPQIoE5N+iRMRQ/M1NHY1+E0TtdxWIi3pN11r7d9SLV4XYYdU5OgZFBKeQXULY5tKYG/ZMQj0MPmpksZ8="
# ---

IGNORE_ENV_FILE=true . $DEVTOOLS_BASH_DEVTOOLS_HOME/setup.sh
