echo "Modifying .bash_profile with Dev Tools env vars."
echo -e "$(
  cat <<END
# <DEVTOOLS>
# Environment variables
# =====================
export DEV_HOME=$DEVTOOLS_BASH_DEV_HOME
export REPO_HOME=$DEVTOOLS_BASH_REPO_HOME
export DEVTOOLS_HOME=$DEVTOOLS_BASH_DEVTOOLS_HOME
export TOOLS_HOME=$DEVTOOLS_BASH_TOOLS_HOME
export TOOLS_BIN_HOME=$DEVTOOLS_BASH_TOOLS_BIN_HOME
export DEVTOOLS_REPO_NAME=$DEVTOOLS_BASH_REPO_NAME
export GITHUB_USER=$DEVTOOLS_GITHUB_USER
# </DEVTOOLS>
END
)" >>~/.bash_profile

mkdir -p $DEVTOOLS_BASH_DEV_HOME
mkdir -p $DEVTOOLS_BASH_REPO_HOME
mkdir -p $DEVTOOLS_BASH_DEVTOOLS_HOME
mkdir -p $DEVTOOLS_BASH_TOOLS_HOME
mkdir -p $DEVTOOLS_BASH_TOOLS_BIN_HOME
