---
- name: Install projects bin tools
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Find projects bin files
      ansible.builtin.find:
        paths: "{{ workbench_dir }}/projects/bin"
        file_type: file
      register: projects_bin_files

    - name: Install projects bin files
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ tools_bin_home }}/{{ item.path | basename }}"
        mode: "0755"
        remote_src: true
      loop: "{{ projects_bin_files.files }}"

    - name: Find projects completion files
      ansible.builtin.find:
        paths: "{{ workbench_dir }}/projects/completion"
        file_type: file
      register: projects_completion_files

    - name: Add projects completions to ~/.bashrc
      ansible.builtin.blockinfile:
        path: "~/.bashrc"
        create: true
        mode: "0644"
        marker: "# {mark} devtools:completion-{{ item.path | basename }}"
        block: "{{ lookup('file', item.path) }}"
      loop: "{{ projects_completion_files.files }}"
