---
- name: Install Telepresence
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Install Telepresence (macOS via Homebrew)
      community.general.homebrew:
        name: datawire/blackbird/telepresence
        state: present
      when: ansible_facts['system'] == 'Darwin'
