---
- name: Install yq
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Install yq (macOS via Homebrew)
      community.general.homebrew:
        name: yq
        state: present
      when: ansible_system == 'Darwin'

    - name: Install yq (Windows via Chocolatey)
      chocolatey.chocolatey.win_chocolatey:
        name: yq
        state: present
      when: ansible_os_family == 'Windows'
